spring:
  application:
    name: train-ticket-member
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
      enabled: on
  profiles:
    active: dev
  main:
    banner-mode: off
  jackson:
    time-zone: GMT+8
    serialization:
      write-enums-using-to-string: on
      write-dates-as-timestamps: false
      fail-on-empty-beans: off
    default-property-inclusion: always
    deserialization:
      fail-on-unknown-properties: off
    date-format: yyyy-MM-dd HH:mm:ss
management:
  endpoints:
    web:
      exposure:
        include: metrics,info,health,restart,refresh,resume
  endpoint:
    health:
      show-details: always
  health:
    mail:
      enabled: on
  info:
    git:
      enabled: on
      mode: full
