server:
  port: 8001
  tomcat:
    threads:
      # 最大线程数
      max: 20
      # 最小空闲线程数
      min-spare: 10
    # spring-boot最大请求数=最大连接数+最大等待数（默认：8192+100=8292）
    # 最大连接数（默认8192）
    max-connections: 30
    # 最大等待数（默认100）
    accept-count: 10
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/train_ticket_member?stringtype=unspecified&timezone=Asia/Shanghai
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: train-ticket-member
      auto-commit: on
      connection-timeout: 30000
      max-lifetime: 600000
      idle-timeout: 300000
      connection-test-query: select 1
      validation-timeout: 1500
      minimum-idle: 2
      maximum-pool-size: 10
      schema: public
