server:
  servlet:
    context-path: /batch
spring:
  application:
    name: train-ticket-batch
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
      enabled: on
  profiles:
    active: dev
  main:
    banner-mode: log
  jackson:
    time-zone: GMT+8
    serialization:
      write-enums-using-to-string: on
      write-dates-as-timestamps: false
      fail-on-empty-beans: off
    default-property-inclusion: always
    deserialization:
      fail-on-unknown-properties: off
    date-format: yyyy-MM-dd HH:mm:ss
management:
  endpoints:
    web:
      exposure:
        include: metrics,info,health,restart,refresh,resume
  endpoint:
    health:
      show-details: always
  health:
    mail:
      enabled: on
  info:
    git:
      enabled: on
      mode: full
mybatis-plus:
  configuration:
    # 全局启用或禁用延迟加载
    lazy-loading-enabled: on
    # 当启用时，有延迟加载属性的对象在被调用时将会完全加载任意属性。否则，每种属性将会按需要加载。
    aggressive-lazy-loading: off
    # 是否可以使用列的别名
    use-column-label: on
    # 当查询数据为空时字段返回为null，不设置这个字段为true的话查询的数据为null时，字段将被隐藏
    call-setters-on-nulls: on
  global-config:
    db-config:
      logic-delete-value: -1
      logic-not-delete-value: 0
      logic-delete-field: deleted
    banner: off
